name: Debugging helper

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
    - name: Get ElevenLabs voice name
      env:
        ELEVENLABS_VOICE_ID: ${{ secrets.ELEVENLABS_VOICE_ID }}
        ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      run: |
        set -o pipefail

        curl --fail-with-body --silent --show-error \
          --header "xi-api-key: $ELEVENLABS_API_KEY" \
          "https://api.elevenlabs.io/v1/voices/$ELEVENLABS_VOICE_ID" |
          jq -r '"Voice: \(.name)
        Category: \(.category)
        Description: \(.description // "none")"'

