name: Debugging helper

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
    - name: Get ElevenLabs voice ID
      env:
        VOICE_ID: ${{ vars.ELEVENLABS_VOICE_ID }}
      run: |
        echo "Part 1: ${VOICE_ID:0:10}"
        echo "Part 2: ${VOICE_ID:10:10}"
        echo "Part 3: ${VOICE_ID:20}"
